[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.23.6"

[context.branch-deploy]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=63142000, must-revalidate"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63142000; includeSubdomains"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
