---
name: CI

"on":
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Zola
        uses: https://github.com/taiki-e/install-action@zola
      - name: Build
        run: zola build

  release:
    name: Create release
    if: >-
      forgejo.ref_type == 'tag' &&
      forgejo.repository_owner == 'charlesrocket'

    uses: charlesrocket/reusable/.forgejo/workflows/release.yml@trunk
    with:
      skip-assets: true
